AWSTemplateFormatVersion: '2010-09-09'
Description: Compute stack with EC2

Resources:
  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: my-key-pair
      SecurityGroupIds:
        - !ImportValue WebSecurityGroup
      SubnetId: !ImportValue PublicSubnet
      ImageId: ami-09483685933501e93
      

Outputs:
  EC2InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
